[package]
name = "td-ql-logic-sys"
version = "0.1.0"
edition = "2021"
links = "sgx_tdx_logic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.65.1"
